Greeting.create(text: 'Hey there, have a day full of joy!')
Greeting.create(text: 'Enjoy your day to the fullest and savor every moment.')
Greeting.create(text: 'Hi, wishing you a day full of positive energy!')
Greeting.create(text: 'Wishing you a wonderful day filled with happiness.')
Greeting.create(text: "It's a new day, make it a fantastic one!")
Greeting.create(text: 'Good morning! I hope your day is wonderful.')
Greeting.create(text: 'Wishing you a wonderful and productive day.')
Greeting.create(text: 'Make it a fantastic day by being your amazing self.')
Greeting.create(text: 'May your day be filled with joy and all your dreams come true.')
Greeting.create(text: 'Wishing you a day filled with success and achievements.')